nodeLinker: pnp

packageExtensions:
  gatsby@*:
    dependencies:
      babel-plugin-styled-components: "*"
  remark-preset-prettier@*:
    dependencies:
      remark-lint-emphasis-marker: ^2.0.1
      remark-lint-list-item-indent: ^2.0.1
      remark-lint-list-item-spacing: ^3.0.0
      remark-lint-maximum-line-length: ^2.0.3
      remark-lint-no-literal-urls: ^2.0.1
      remark-lint-ordered-list-marker-value: ^2.0.1
      remark-lint-table-cell-padding: ^3.0.0
      remark-lint-table-pipe-alignment: ^2.0.1
  theo@*:
    dependencies:
      optimist: ^0.6.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.0.2.cjs
