extends: substitution
message: "Use the American spelling '%s' instead of '%s'."
link: 'https://orbit.kiwi/content/grammar-and-mechanics/#spelling'
ignorecase: true
level: warning
action:
  name: replace
swap:
  aeroplane: airplane
  ageing: aging
  aluminium: aluminum
  analogue: analog
  analyse: analyze
  analysed: analyzed
  annexe: annex
  apologise: apologize
  behaviour: behavior
  busses: buses
  centre: center
  cheque: check
  civilisation: civilization
  civilise: civilize
  colour: color
  cosy: cozy
  cypher: cipher
  dependant: dependent
  defence: defense
  dialogue: dialog
  draught: draft
  enquiry: inquiry
  enrol: enroll
  enrolment: enrollment
  favourite: favorite
  fibre: fiber
  flavour: flavor
  focussed: focused
  fuelled: fueled
  fuelling: fueling
  fulfil: fulfill
  grey: gray
  humour: humor
  honour: honor
  initialled: initialed
  initialling: initialing
  instil: instill
  jewellery: jewelry
  labelling: labeling
  labelled: labeled
  labour: labor
  licence: license
  likeable: likable
  litre: liter
  liveable: livable
  metre: meter
  modelling: modeling
  moustache: mustache
  neighbour: neighbor
  normalise: normalize
  offence: offense
  organisation: organization
  organise: organize
  organised: organized
  organising: organizing
  orientated: oriented
  paralyse: paralyze
  plough: plow
  practise: practice
  pretence: pretense
  programme: program
  pyjamas: pajamas
  rateable: ratable
  realise: realize
  realised: realized
  recognise: recognize
  recognised: recognized
  rumour: rumor
  saleable: salable
  sceptic: skeptic
  signalling: signaling
  sizeable: sizable
  skilful: skillful
  speciality: specialty
  standardise: standardize
  standardised: standardized
  theatre: theater
  travelled: traveled
  traveller: traveler
  travelling: traveling
  unshakeable: unshakable
  wilful: willful
  yoghurt: yogurt
