extends: existence
message: "Place the currency symbol before the number."
link: 'https://orbit.kiwi/content/grammar-and-mechanics/#date-time'
level: error
nonword: true
tokens:
  - '\d (\$|€|£|￡)'
  - '\d(\$|€|£|￡)'