extends: substitution
message: "Use '%s' instead of '%s'."
link: 'https://developers.google.com/style/abbreviations'
ignorecase: true
level: warning
nonword: true
action:
  name: replace
swap:
  '\b(?:eg|e\.g\.|eg\.|e. g.)[\s,]': for example
  '\b(?:ie|i\.e\.|ie\.|i. e.)[\s,]': that is
