name: Lint prose

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master
    paths:
      - docs/src/documents/**
      - .github/styles/**
      - .vale.ini
      - packages/orbit-components/src/**/*.md

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Vale
        uses: errata-ai/vale-action@master
        with:
          files: '["docs/src/documentation", "docs/src/snippets"]'
          onlyAnnotateModifiedLines: true
        env:
          # Required
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
